In [22]:
from sqlalchemy import create_engine
import pandas as pd
import time

In [ ]:
engine = create_engine('postgresql://postgres:postgres@localhost:5433/ny_taxi')

--- Yellow Taxi Data (short file) ---

In [6]:
# Read a sample of the data
df = pd.read_csv('./taxi_zone_lookup.csv')

In [7]:
# Display first rows csv
df.head()

   LocationID        Borough                     Zone service_zone
0           1            EWR           Newark Airport          EWR
1           2         Queens              Jamaica Bay    Boro Zone
2           3          Bronx  Allerton/Pelham Gardens    Boro Zone
3           4      Manhattan            Alphabet City  Yellow Zone
4           5  Staten Island            Arden Heights    Boro Zone

In [8]:
# Check data types
df.dtypes

LocationID      int64
Borough           str
Zone              str
service_zone      str
dtype: object

In [9]:
# Check data shape
df.shape

(265, 4)

In [24]:
df.to_sql(name='yellow_taxi', con=engine, if_exists='replace', index=False, chunksize=1000)

265

# --- Green Taxi Data (Large file, using chunks) ---

In [10]:
# Read and Ingest
df_green = pd.read_parquet('green_tripdata_2025-11.parquet')

In [11]:
# Display first rows csv
df_green.head()

,VendorID,lpep_pickup_datetime,lpep_dropoff_datetime,store_and_fwd_flag,RatecodeID,PULocationID,DOLocationID,passenger_count,trip_distance,fare_amount,...,mta_tax,tip_amount,tolls_amount,ehail_fee,improvement_surcharge,total_amount,payment_type,trip_type,congestion_surcharge,cbd_congestion_fee
0,2,2025-11-01 00:34:48,2025-11-01 00:41:39,N,1.0,74,42,1.0,0.74,7.2,...,0.5,1.94,0.0,NaN,1.0,11.64,1.0,1.0,0.00,0.0
1,2,2025-11-01 00:18:52,2025-11-01 00:24:27,N,1.0,74,42,2.0,0.95,7.2,...,0.5,0.00,0.0,NaN,1.0,9.70,2.0,1.0,0.00,0.0
2,2,2025-11-01 01:03:14,2025-11-01 01:15:24,N,1.0,83,160,1.0,2.19,13.5,...,0.5,5.00,0.0,NaN,1.0,21.00,1.0,1.0,0.00,0.0
3,2,2025-11-01 00:10:57,2025-11-01 00:24:53,N,1.0,166,127,1.0,5.44,24.7,...,0.5,0.50,0.0,NaN,1.0,27.70,1.0,1.0,0.00,0.0
4,1,2025-11-01 00:03:48,2025-11-01 00:19:38,N,1.0,166,262,1.0,3.20,18.4,...,1.5,1.00,0.0,NaN,1.0,24.65,1.0,1.0,2.75,0.0

In [12]:
# Check data types
df_green.dtypes

VendorID                          int32
lpep_pickup_datetime     datetime64[us]
lpep_dropoff_datetime    datetime64[us]
store_and_fwd_flag                  str
RatecodeID                      float64
PULocationID                      int32
DOLocationID                      int32
passenger_count                 float64
trip_distance                   float64
fare_amount                     float64
extra                           float64
mta_tax                         float64
tip_amount                      float64
tolls_amount                    float64
ehail_fee                       float64
improvement_surcharge           float64
total_amount                    float64
payment_type                    float64
trip_type                       float64
congestion_surcharge            float64
cbd_congestion_fee              float64
dtype: object

In [13]:
# Check data shape
df_green.shape

(46912, 21)

In [18]:
# We use lpep_pickup_datetime to ensure the schema is correct in Postgres
df_green.lpep_pickup_datetime = pd.to_datetime(df_green.lpep_pickup_datetime)
df_green.lpep_dropoff_datetime = pd.to_datetime(df_green.lpep_dropoff_datetime)

In [20]:
print(f"Ingesting taxi data ({len(df_green)} rows) in chunks...")

Ingesting taxi data (46912 rows) in chunks...

In [23]:
start_time = time.time()

# if_exists='replace' for the first chunk to create the table
# chunksize=100000 tells pandas how many rows to send at once
df_green.to_sql(name='green_taxi', con=engine, if_exists='replace', index=False, chunksize=10000)
    
end_time = time.time()
print(f"Finished! Ingestion took {end_time - start_time:.2f} seconds.")

Finished! Ingestion took 5.21 seconds.